spring.application.name=SSOProjectUsingOAuth

# Oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=sritam
spring.datasource.password=lion

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Port number
server.port=4041

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${google.client-id}
spring.security.oauth2.client.registration.google.client-secret=${google.client-secret}
spring.security.oauth2.client.registration.google.scope=openid,email,profile
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth?prompt=select_account

# Github OAuth2
spring.security.oauth2.client.registration.github.client-id=${github.client-id}
spring.security.oauth2.client.registration.github.client-secret=${github.client-secret}
spring.security.oauth2.client.registration.github.scope=read:user,user:email
spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize?prompt=select_account