spring.application.name=SSOProjectUsingManualOAuth

server.port=4041

# Oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=sritam
spring.datasource.password=lion

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# OAuth2 credentials from environment variables
google.client-id=${GOOGLE_CLIENT_ID}
google.client-secret=${GOOGLE_CLIENT_SECRET}

github.client-id=${GITHUB_CLIENT_ID}
github.client-secret=${GITHUB_CLIENT_SECRET}