spring.application.name=SSOProject

# Oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=sritam
spring.datasource.password=lion

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Port number
server.port=4041

# Authorization uri
oauth2.authorization-base-url=/oauth2/authorization/

#Logging
logging.level.com.sri=INFO
logging.level.org.springframework.security=INFO